name: Pre-commit Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project dependencies for pyright check
        run: |
          python -m venv venv
          venv\Scripts\activate.bat
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install -r requirements.txt

      - name: Run pre-commit hooks
        run: |
          venv\Scripts\activate.bat
          pre-commit run --all-files
